# Generated by Django 2.2.5 on 2020-09-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200917_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('github', 'GitHub'), ('kakao', 'Kakao')], default='email', max_length=50),
        ),
    ]
